### ISSUE TITLE
getTargetFragment() NPE in some fragments

### ISSUE THREAD

**Issue by egslava** [VictorAlbertos/RxActivityResult#5] opened 2016-05-06 12:10 UTC
Buenas tardes Victor! :-)
Sorry, can't do demo project now. But it seems, like when you have complex UI there's NPE in that code:

```
        @Nullable private Fragment getTargetFragment(List<Fragment> fragments) {
            if (fragments == null) return null;

            for (Fragment fragment : fragments) {
                if(fragment != null && fragment.isVisible() && fragment.getClass() == clazz) {
                    return fragment;
      // NPE IS HERE SEE           |
      //                           v
                } else if (fragment.getChildFragmentManager() != null) {     //   <------ THAT LINE
                    List<Fragment> childFragments = fragment.getChildFragmentManager().getFragments();
                    return getTargetFragment(childFragments);
                }
            }

            return null;
        }
```

(RxActivityResult.java line 139)

It seems, like fragments array have target Fragment, but ALSO has null element inside. So if you just skipped null-element - NPE would dismiss.

In my UI I have fragments (cause of navigation drawer) and nested fragments (in ViewPager). RxPaparazzo code is called from nested fragment.

**Comment by egslava** [comment] 2016-05-06 12:22
Sorry, forgot stack trace:
```
05-06 15:19:20.807 28896-28896/com.egslava.example E/AndroidRuntime: FATAL EXCEPTION: main
   Process: com.egslava.example, PID: 28896
   java.lang.RuntimeException: Unable to destroy activity {com.egslava.example/rx_activity_result.HolderActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v4.app.FragmentManager android.support.v4.app.Fragment.getChildFragmentManager()' on a null object reference
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3831)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849)
       at android.app.ActivityThread.-wrap5(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v4.app.FragmentManager android.support.v4.app.Fragment.getChildFragmentManager()' on a null object reference
       at rx_activity_result.RxActivityResult$Builder.getTargetFragment(RxActivityResult.java:145)
       at rx_activity_result.RxActivityResult$Builder.access$300(RxActivityResult.java:50)
       at rx_activity_result.RxActivityResult$Builder$4.response(RxActivityResult.java:126)
       at rx_activity_result.HolderActivity.onDestroy(HolderActivity.java:79)
       at android.app.Activity.performDestroy(Activity.java:6422)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1142)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3818)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849) 
       at android.app.ActivityThread.-wrap5(ActivityThread.java) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398) 
       at android.os.Handler.dispatchMessage(Handler.java:102) 
       at android.os.Looper.loop(Looper.java:148) 
       at android.app.ActivityThread.main(ActivityThread.java:5417) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by egslava** [comment] 2016-05-06 13:23
Updated demo project

**Comment by egslava** [comment] 2016-05-06 13:34
https://github.com/egslava/bug-report-rx-paparazzo-nested-fragments
Added gif/youtube. Please, pay attention to it.

**Comment by VictorAlbertos** [comment] 2016-05-06 15:27
привет @egslava  ;)

Try the new release, please: 

`compile "com.github.FuckBoilerplate:RxPaparazzo:0.0.6"`

It seems to work. But I do not know if there is some "internal bleeding" xD. It just seems to me a little weird that `getFragments()` may return null values. 

And thanks for your feedback, again.

**Comment by egslava** [comment] 2016-05-06 17:15
Much gracias, Victor!
It seems to work, but I'm not sure about "Don't keep activities". Could you, please, test it again in this mode? It fails on my device (nexus 5) :-(

**Comment by egslava** [comment] 2016-05-06 17:19
```
05-06 20:17:51.040 11370-11370/ru.egslava.rxfluxtest E/AndroidRuntime: FATAL EXCEPTION: main
 Process: ru.egslava.rxfluxtest, PID: 11370
 java.lang.RuntimeException: Unable to destroy activity {ru.egslava.rxfluxtest/rx_activity_result.HolderActivity}: rx.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3831)
     at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849)
     at android.app.ActivityThread.-wrap5(ActivityThread.java)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:148)
     at android.app.ActivityThread.main(ActivityThread.java:5417)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
  Caused by: rx.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
     at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:374)
     at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:371)
     at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
     at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
     at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
     at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:204)
     at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
     at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onNext(OperatorOnErrorResumeNextViaFunction.java:153)
     at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:74)
     at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:391)
     at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:353)
     at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:838)
     at rx.observers.Subscribers$5.onNext(Subscribers.java:229)
     at rx.internal.operators.OperatorZip$Zip.tick(OperatorZip.java:264)
     at rx.internal.operators.OperatorZip$Zip$InnerSubscriber.onNext(OperatorZip.java:335)
     at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:74)
     at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:268)
     at rx.Subscriber.setProducer(Subscriber.java:211)
     at rx.internal.operators.OperatorMap$MapSubscriber.setProducer(OperatorMap.java:99)
     at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:79)
     at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:75)
     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
     at rx.Observable.unsafeSubscribe(Observable.java:8452)
     at rx.internal.operators.OperatorZip$Zip.start(OperatorZip.java:214)
     at rx.internal.operators.OperatorZip$ZipSubscriber.onNext(OperatorZip.java:156)
     at rx.internal.operators.OperatorZip$ZipSubscriber.onNext(OperatorZip.java:122)
     at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:268)
     at rx.Subscriber.setProducer(Subscriber.java:209)
     at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:79)
     at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:75)
     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
     at rx.Observable.unsafeSubscribe(Observable.java:8452)
     at rx.internal.util.ScalarSynchronousObservable$4.call(ScalarSynchronousObservable.java:227)
 	at rx.internal.util.ScalarSynchrono
```

StackTrace. Interestingly, that the original app I was working for is stable now. Crashes only test app.

**Comment by VictorAlbertos** [comment] 2016-05-06 17:31
Well, I don't know. But maybe at some point you are calling some method/variable from the fragment directly, instead of calling it using the wrapper instance  `targetUI()`.

Anyway, I'm testing your project and I can't reproduce the issue. It seems It works fine.

**Comment by egslava** [comment] 2016-05-07 08:21
Steps to reproduce:
https://youtu.be/83qBSCVuynU

Ensure you have checked "Don't keep activities" checkbox.

**Comment by egslava** [comment] 2016-05-07 08:34
Ow, very-very sorry. The problem was in my logging function that uses context instance for Toast. What's strange is a stack trace. It doesn't contain any line of "test app". So sorry I disturbed you. But, perhaps, you can answer - is there a way to throw a little bit more elegant exceptions?

**Comment by VictorAlbertos** [comment] 2016-05-07 09:09
I don't think so. This error happens out of the scope of rxactivityresult. I mean it is due to the fact that the instance used to access the context has been "recreated" by android system after some configuration changes or, in you case, because you had active the option don't keep activities alive. 

In the readme I encourage to pay attention at this point (use targetUI()!), because it could lead to this scenario ;)

**Comment by egslava** [comment] 2016-05-07 09:13
> In the readme I encourage to pay attention at this point (use targetUI()!), because it could lead to this scenario ;)

No, no, that's okay. That's not your error. I'm about RxJava. I know, that it's not a theme of that thread, but don't you know how todo errors a little bit readable?
For instance, I have a code:
```
fun BaseFragment.callGallery(view: View){
    view.clicks().bindToLifecycle(this).subscribe {
        RxPaparazzo.takeImage(this)
        .usingGallery()
        .subscribe { response ->
            throw RuntimeException("Where is this exception from?")
        }
    }
}
```
In Utils.kt. But in stacktrace there's no any hint about Utils.kt or about any of my file.
```
05-07 12:11:48.246 10966-10966/ru.egslava.rxfluxtest E/AndroidRuntime: FATAL EXCEPTION: main
 Process: ru.egslava.rxfluxtest, PID: 10966
 java.lang.RuntimeException: Unable to destroy activity {ru.egslava.rxfluxtest/rx_activity_result.HolderActivity}: rx.exceptions.OnErrorNotImplementedException: Where is this exception from?
     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3831)
     at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849)
     at android.app.ActivityThread.-wrap5(ActivityThread.java)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:148)
     at android.app.ActivityThread.main(ActivityThread.java:5417)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
  Caused by: rx.exceptions.OnErrorNotImplementedException: Where is this exception from?
     at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:374)
     at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:371)
     at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
     at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
     at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
     at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:204)
     at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
     at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onNext(OperatorOnErrorResumeNextViaFunction.java:153)
     at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:74)
     at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:391)
     at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:353)
     at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:838)
     at rx.observers.Subscribers$5.onNext(Subscribers.java:229)
     at rx.internal.operators.OperatorZip$Zip.tick(OperatorZip.java:264)
     at rx.internal.operators.OperatorZip$Zip$InnerSubscriber.onNext(OperatorZip.java:335)
     at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:74)
     at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:268)
     at rx.Subscriber.setProducer(Subscriber.java:211)
     at rx.internal.operators.OperatorMap$MapSubscriber.setProducer(OperatorMap.java:99)
     at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:79)
     at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:75)
     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
     at rx.Observable.unsafeSubscribe(Observable.java:8452)
     at rx.internal.operators.OperatorZip$Zip.start(OperatorZip.java:214)
     at rx.internal.operators.OperatorZip$ZipSubscriber.onNext(OperatorZip.java:156)
     at rx.internal.operators.OperatorZip$ZipSubscriber.onNext(OperatorZip.java:122)
     at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:268)
     at rx.Subscriber.setProducer(Subscriber.java:209)
     at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:79)
     at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:75)
     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
     at rx.Observable.unsafeSubscribe(Observable.java:8452)
     at rx.internal.util.ScalarSynchronousObservable$4.call(ScalarSynchronousObservable.java:227)
     at rx.internal.util.ScalarSynchronousObservable$4.call(ScalarSynchronousObservable.java:220)
     at rx.Observable.unsafeSubscribe(Observable.java:8452)
     at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
```

**Comment by VictorAlbertos** [comment] 2016-05-07 09:18
You can try something like this:

```java
fun BaseFragment.callGallery(view: View){
    view.clicks().bindToLifecycle(this).subscribe {
        RxPaparazzo.takeImage(this)
        .usingGallery()
        .subscribe { response ->
            ....
        , error -> Log.e("callgallery", error.getMessage())}
    }
}
```

**Comment by egslava** [comment] 2016-05-07 09:22
I'd rather prefer:
```
.subscribe ({ response ->
            ....
        }, { it.printStackTrace() })
```

But it seems to be boilerplate :-/ Okay, sorry, can't disturb you anymore.

**Comment by VictorAlbertos** [comment] 2016-05-07 09:30
Don't worry. I appreciate the feedback ;)

I'm going to close the issue. Feel to reopen it if you need to do it.

**Closed by VictorAlbertos** 2016-05-07 09:30 UTC
